### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by jpylypiw** [EndBug/game-tracker#12]
Hi there!

I am interested in your Discord bot. I am not a Discord poweruser so I don't know what Discord bots do in general.
Can you add some screenshots or example data in your readme?
This would be very useful for everyone visiting your project.
Alternatively you could add a invite to a example Discord Server.

KR,
Jochen

**Comment by EndBug** [comment]
Sure thing, I'll try to do it in the next days ;)

**Comment by EndBug** [comment]
@jpylypiw Thanks for the idea, it has been implemented with #13 
@all-contributors please add @jpylypiw for ideas
