### ISSUE TITLE
Don't sort r6s operators table alphabetically

### ISSUE THREAD

**Issue by danielwerg** [EndBug/game-tracker#280]
In [this](https://github.com/EndBug/game-tracker/commit/eed934a0b09bd99589e9b93e662a574674aab462#diff-4b315cbcfe3867d476adacb21e453ba964e80db9d49efd61b84f66bc80222464) commit you started to sort tables for r6s stuff alphabetically which doesn't really makes sense for operators, I'd argue it's harder to find operator in that order compare to default (same as in-game, sorted by release date and unit/org).

Would you consider making exception for operators table?

**Comment by EndBug** [comment]
How should I order them? Is the order from `r6api.js` the same as the in-game order?

**Comment by danielwerg** [comment]
Yeah, just don't apply any sorting to it.

**Comment by EndBug** [comment]
Here we go, operators are now in the default order: https://game-tracker.js.org/#/r6/r6_names

**Comment by EndBug** [comment]
@all_contributors please add @danielwerg for their docs contribution

**Comment by EndBug** [comment]
@all-contributors please add @danielwerg for their docs contribution
