### ISSUE TITLE
Game commands allow mentions in error responses

### ISSUE THREAD

**Issue by EndBug** [EndBug/game-tracker#65]
Reported by @DuckMasterAl on Discord.

A message like this can make the bot reply with a mention:
```
-r6 general `\`@here
```

**Comment by DuckMasterAl** [comment]
The solution is to add `allowed_mentions`
--
**Discord.py (requires v1.4.0)** - add `, allowed_mentions=discord.AllowedMentions(roles=False, everyone=False)` after the output of your command.
**Discord.JS (requires v12.2.0)** - add `, {allowedMentions: {parse: []}}` after the output of your command.
**Discord docs:** <https://discord.com/developers/docs/resources/channel#allowed-mentions-object>

**Comment by EndBug** [comment]
@all-contributors please add @DuckMasterAl for bug

**Comment by EndBug** [comment]
@DuckMasterAl I've tried using that option, but the problem is still there: do you know any other way to safely resolve the issue?

**Comment by DuckMasterAl** [comment]
> @DuckMasterAl I've tried using that option, but the problem is still there: do you know any other way to safely resolve the issue?

Are you using the right version?

**Comment by EndBug** [comment]
Yup

**Comment by EndBug** [comment]
This last commit seems to have solved the problem.
I ended up just replacing every non-escaped `@here` and `@everyone`: this isn't really the best solution but it does the job.
Also, for the bot to mention anybody there has to be someone sending a mention before: that means that it could be prevented by just removing the permission for the users to write those mentions in the first place.
I'm going to close this for now, thanks for the report :)

**Comment by DuckMasterAl** [comment]
> This last commit seems to have solved the problem.
> 
> I ended up just replacing every non-escaped `@here` and `@everyone`: this isn't really the best solution but it does the job.
> 
> Also, for the bot to mention anybody there has to be someone sending a mention before: that means that it could be prevented by just removing the permission for the users to write those mentions in the first place.
> 
> I'm going to close this for now, thanks for the report :)

Ok, but what about role mentions?

**Comment by EndBug** [comment]
Oh, yeah, I forgot about that. If you can find a regex that will match those as well tell me, I'll use that instead

**Comment by DuckMasterAl** [comment]
I won't be able to help you with that as I code in `discord.py` and from what I know the only way to do that is by using `allowed_mentions`
